name: Create release and binaries

on:
  workflow_dispatch:

env:
  TAGNAME: "abusiv-ok"
  FILE_REQ: "req.txt"
  FILE_PY: "abusiv.py"
  NAME_LINUX: "abusiv-linux.tar"
  NAME_WINDOWS: "abusiv-windows.zip"

jobs:
  job-one:
    name: Build binaries
    strategy:
      matrix:
        os: [ubuntu-20.04,windows-2019]
    runs-on: ${{ matrix.os }}

    steps:

    - name: Pull the repo
      uses: actions/checkout@v3

    - name: Setup Python (1)
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.6"
    - name: Setup Python (2)
      run: |
        pip install -r "${{ env.FILE_REQ }}"

    - name: Linux (Build binary)
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      run: |
        pip install pyinstaller
        pyinstaller --onefile "${{ env.FILE_PY }}"
        mv dist abusiv-linux
        mv README.md abusiv-linux/README.md
        tar -cvf "${{ env.NAME_LINUX }}" abusiv-linux

    - name: Linux (Upload artifact)
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      uses: actions/upload-artifact@v3
      with:
        name: "${{ env.NAME_LINUX }}"
        path: "${{ env.NAME_LINUX }}"

    - name: Windows (Build binary)
      if: ${{ matrix.os == 'windows-2019' }}
      run: |
        pip install PyInstaller
        python -m PyInstaller --onefile "${{ env.FILE_PY }}"
        mv dist abusiv-windows
        mv README.md abusiv-windows64/README.md
        Compress-Archive abusiv-windows "${{ env.NAME_WINDOWS }}"

    - name: Windows (Upload artifact)
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      uses: actions/upload-artifact@v3
      with:
        name: "${{ env.NAME_LINUX }}"
        path: "${{ env.NAME_LINUX }}"

  job-two:
    name: Create release and add the assets
    needs: job-one
    runs-on: ubuntu-latest
    steps:

    - name: Download artifact (Linux)
      uses: actions/download-artifact@v2.1.1
      with:
        name: "${{ env.NAME_LINUX }}"

    - name: Download artifact (Windows)
      uses: actions/download-artifact@v2.1.1
      with:
        name: "${{ env.NAME_WINDOWS }}"

    - name: Create release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: "${{ env.TAGNAME }}"
        release_name: "${{ env.TAGNAME }}"
        draft: false
        prerelease: false

    - name: Ubuntu / Linux (Upload Release Asset)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: "${{ env.NAME_LINUX }}"
        asset_name: "${{ env.NAME_LINUX }}"
        asset_content_type: application/octet-stream

    - name: Windows (Upload Release Asset)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: "${{ env.NAME_WINDOWS }}"
        asset_name: "${{ env.NAME_WINDOWS }}"
        asset_content_type: application/octet-stream
